<a href="https://colab.research.google.com/github/Vishu31k/IML-Project/blob/main/Iml_assignment_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import shap
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

Load the Dataset

In [2]:
df = pd.read_csv("/content/creditcard.csv")

Data Overview

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

Check Class Distribution

In [5]:
print(df['Class'].value_counts())

Class
0    284315
1       492
Name: count, dtype: int64


In [6]:
X = df.drop('Class', axis=1)
y = df['Class']


In [7]:
# Step 1: Load data
df = pd.read_csv("/content/creditcard.csv")

# Step 2: Check for missing values
print("Missing values in each column:\n", df.isnull().sum())

# Step 3: Impute or drop missing values
# Option A: Drop rows with missing values (if very few)
df = df.dropna()

# Option B (alternative): Fill missing values with column mean (if needed instead of drop)
# df = df.fillna(df.mean())

# Step 4: Split features and target
X = df.drop('Class', axis=1)
y = df['Class']

# Step 5: Train-Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# Step 6: Check final shapes
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)


Missing values in each column:
 Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64
X_train shape: (227845, 30)
X_test shape: (56962, 30)
y_train shape: (227845,)
y_test shape: (56962,)


In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [9]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (227845, 30)
X_test shape: (56962, 30)
y_train shape: (227845,)
y_test shape: (56962,)


In [10]:
pip install xgboost lightgbm


In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, matthews_corrcoef

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier

import xgboost as xgb
import lightgbm as lgb

# Load and split data
df = pd.read_csv("/content/creditcard.csv")
X = df.drop('Class', axis=1)
y = df['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# Define models
models = {
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "KNN": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB(),
    "MLP (Neural Net)": MLPClassifier(hidden_layer_sizes=(100,), max_iter=300, random_state=42),
    "XGBoost": xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42),
    "LightGBM": lgb.LGBMClassifier(random_state=42)
}

# Evaluation function
def evaluate_model(name, model):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    cm = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel()

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    mcc = matthews_corrcoef(y_test, y_pred)
    tpr = tp / (tp + fn)
    tnr = tn / (tn + fp)

    print(f"\n=== {name} ===")
    print("Confusion Matrix:\n", cm)
    print(f"Accuracy: {acc:.4f}")
    print(f"Precision: {prec:.4f}")
    print(f"Recall (TPR): {tpr:.4f}")
    print(f"TNR (Specificity): {tnr:.4f}")
    print(f"F1 Score: {f1:.4f}")
    print(f"MCC: {mcc:.4f}")

# Loop through models
for name, model in models.items():
    evaluate_model(name, model)



=== Random Forest ===
Confusion Matrix:
 [[56859     5]
 [   18    80]]
Accuracy: 0.9996
Precision: 0.9412
Recall (TPR): 0.8163
TNR (Specificity): 0.9999
F1 Score: 0.8743
MCC: 0.8763

=== Decision Tree ===
Confusion Matrix:
 [[56840    24]
 [   25    73]]
Accuracy: 0.9991
Precision: 0.7526
Recall (TPR): 0.7449
TNR (Specificity): 0.9996
F1 Score: 0.7487
MCC: 0.7483

=== KNN ===
Confusion Matrix:
 [[56864     0]
 [   95     3]]
Accuracy: 0.9983
Precision: 1.0000
Recall (TPR): 0.0306
TNR (Specificity): 1.0000
F1 Score: 0.0594
MCC: 0.1748

=== Naive Bayes ===
Confusion Matrix:
 [[56457   407]
 [   33    65]]
Accuracy: 0.9923
Precision: 0.1377
Recall (TPR): 0.6633
TNR (Specificity): 0.9928
F1 Score: 0.2281
MCC: 0.3000

=== MLP (Neural Net) ===
Confusion Matrix:
 [[56864     0]
 [   95     3]]
Accuracy: 0.9983
Precision: 1.0000
Recall (TPR): 0.0306
TNR (Specificity): 1.0000
F1 Score: 0.0594
MCC: 0.1748


/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:05:07] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)



=== XGBoost ===
Confusion Matrix:
 [[56857     7]
 [   19    79]]
Accuracy: 0.9995
Precision: 0.9186
Recall (TPR): 0.8061
TNR (Specificity): 0.9999
F1 Score: 0.8587
MCC: 0.8603
[LightGBM] [Info] Number of positive: 394, number of negative: 227451
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.068877 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7650
[LightGBM] [Info] Number of data points in the train set: 227845, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.001729 -> initscore=-6.358339
[LightGBM] [Info] Start training from score -6.358339

=== LightGBM ===
Confusion Matrix:
 [[56802    62]
 [   37    61]]
Accuracy: 0.9983
Precision: 0.4959
Recall (TPR): 0.6224
TNR (Specificity): 0.9989
F1 Score: 0.5520
MCC: 0.5548
